"""Add per-user telegram fields and delivery preferences

Revision ID: 786187746bcc
Revises: cebd6dce1828
Create Date: 2026-07-11 19:09:27.124808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786187746bcc'
down_revision: Union[str, None] = 'cebd6dce1828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_bot_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('delivery_cadence', sa.String(), nullable=True))
    op.add_column('users', sa.Column('delivery_time_utc', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'delivery_time_utc')
    op.drop_column('users', 'delivery_cadence')
    op.drop_column('users', 'telegram_bot_token')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('interests', 'source')
    # ### end Alembic commands ###
