"""Add interest decay fields

Revision ID: cebd6dce1828
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-07 08:00:49.997893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebd6dce1828'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('engagement_score', sa.Float(), nullable=True))
    op.add_column('interests', sa.Column('last_interacted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interests', 'last_interacted_at')
    op.drop_column('interests', 'engagement_score')
    # ### end Alembic commands ###
